---
- name: Check if vector service file exists
  ansible.builtin.stat:
    path: /lib/systemd/system/vector.service
  register: vector_service_file

- name: Fail if vector service file does not exist
  ansible.builtin.fail:
    msg: "Vector service file does not exist"
  when: not vector_service_file.stat.exists

- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enables: false
    name: vector.service
    state: started
  when: ansible_facts['os_family'] != "Debian"

