---
- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!any'
          - os_family

    - name: Ensure Python 3 is installed (Ubuntu/Debian)
      ansible.builtin.apt:
        name:
          - python3
          - python3-distutils
        state: present
      when: ansible_facts['os_family'] == "Debian"
      become: yes

    - name: Ensure Python 3 is installed (CentOS/RHEL/OracleLinux)
      ansible.builtin.yum:
        name:
          - python3
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Set Python 3 as the default interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Gather facts after Python 3 is installed
      ansible.builtin.setup:

  roles:
    - role: /root/vector-role
