---
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
#    pre_build_image: true
    command: /sbin/init
#   privileged: true
#   user: root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        ansible_become: true
verifier:
  name: ansible
